### ISSUE TITLE
How i can fix this

### ISSUE THREAD

**Issue by penchuri** [adh319/Lunox#13]
![](https://media.discordapp.net/attachments/1025000934557892620/1065719221310468186/IMG_4845.png)

**Comment by adh319** [comment]
> ![](https://camo.githubusercontent.com/8655ad619845a3f51e01968c095804721dd2d4798e17420a24ee22ba2ee52703/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f313032353030303933343535373839323632302f313036353731393232313331303436383138362f494d475f343834352e706e67)

Fill everyting on `.env` file or `config.js`
