### ISSUE TITLE
Verification question

### ISSUE THREAD

**Issue by penchuri** [adh319/Lunox#17]
Hi, bro my bot got 76+ servers to join and I'm trying to verified the bot but I think they will make my request say will break the term of use and you know how I can verify the bot?

**Comment by adh319** [comment]
sorry to say this. but this is not the part to ask anything but about lunox

**Comment by penchuri** [comment]
> sorry to say this. but this is not the part to ask anything but about lunox

i think it is cause im using your code Hehe

**Comment by adh319** [comment]
even tho ur using my code... verification thing is related to Discord terms. u should try to ask it with others people that understand more about it.

**Comment by penchuri** [comment]
> even tho ur using my code... verification thing is related to Discord terms. u should try to ask it with others people that understand more about it.

Well thank you my bot finally verified
