### ISSUE TITLE
Lyrics command

### ISSUE THREAD

**Issue by penchuri** [adh319/Lunox#19]
### Bug description

Bot sure if this bug is when you use the lyrics command without putting the song name it will say interaction error it is like you need to put the song name so it will work can you make it when the current song is playing we use the lyrics command without put the song command it will get the lyrics current playing song

### Step to reproduce

No

### Operating system

Linux

### Nodejs version

18

### Errors / Logs

No

**Comment by adh319** [comment]
> ### Bug description
> Bot sure if this bug is when you use the lyrics command without putting the song name it will say interaction error it is like you need to put the song name so it will work can you make it when the current song is playing we use the lyrics command without put the song command it will get the lyrics current playing song
> 
> ### Step to reproduce
> No
> 
> ### Operating system
> Linux
> 
> ### Nodejs version
> 18
> 
> ### Errors / Logs
> No

I will look into it, may be tomorrow. I have to take a rest rn. 👍

**Comment by gamer50082** [comment]
I think this issue is fix. Cannot reproduce (try using node 17 instead if u still getting the issue on the latest update)

**Comment by gamer50082** [comment]
My mistake I was using node 18

**Comment by adh319** [comment]
lyrics wont work anymore
