### ISSUE TITLE
Serverlist 

### ISSUE THREAD

**Issue by penchuri** [adh319/Lunox#20]
### Description of your suggestion

I have a suggestion for the serverlist command. It would be helpful if the command could display the server that the bot is currently in, along with its invite link and the number of users on the server. This would make it easier for owners to manage their servers and keep track of their bot's activity.

**Comment by adh319** [comment]
thanks for the suggestion but i'm not planning to add more feature to the project. reason? too busy & dont have enough time coz i'm focusing on something else right now. if u know the way to make it happen u can make a PR to help the project grow more.

Thanks
