### ISSUE TITLE
Playlist Problem

### ISSUE THREAD

**Issue by alwaysluxury** [adh319/Lunox#24]
### Bug description

So there is this thing or problem, not on the main bot, but when i forked the code and tried it i tried to play a spotify playlist, it worked but instead of playing the same song on the playlist it would play that song but a different version that it found or another song from that artist if there were some songs from that same artist.
This wouldn't happen on every song but on some of them.
I don't know if this is only happening for me or for all, but i haven't seen anyone talk about it so i don't know.

### Step to reproduce

Im not very sure, i tried to find a solution but no luck.

### Operating system

Linux (replit)

### Nodejs version

The version that comes with the bot.

### Errors / Logs

No errors show in the console or the error channel.

**Comment by adh319** [comment]
its just the lavalink issue... try restaring ur lavalink server or use another lavalink server.
