### ISSUE TITLE
non stop reconnecting

### ISSUE THREAD

**Issue by gamer50082** [adh319/Lunox#27]
### Bug description

it says ready but reconnects after 3 sec

### Step to reproduce

readme.md

### Operating system

windows 11 ntfs files sys

### Nodejs version

18

### Errors / Logs

#this is a comment, the below maybe because of reconnection
[COMMAND] play used by BITS_gamer50082#4908 from placeholder 1 (992403526133239829)
[WARN] Errored verification#4815 (1088831672960679956) Error: Invalid URL

**Comment by ukcai696969** [comment]
invalid url request a right url

**Comment by gamer50082** [comment]
the reconnectig error?

**Comment by gamer50082** [comment]
the url is ytmusic and its ok/work

**Comment by adh319** [comment]
> the url is ytmusic and its ok/work

make sure u filled the .env file with correct one.

**Comment by gamer50082** [comment]
[COMMAND] - help executed by BITS_gamer50082#4908 | verification in placeholder 1 (992403526133239829)
[AntiCrash] | [UnhandledRejection_Logs] | [start] : ===============
ExpectedConstraintError > s.string.url
  Invalid URL

  Expected: expected to match an URL

  Received:
  | ''

    at Object.run (N:\Lunox\node_modules\@sapphire\shapeshift\dist\index.js:1595:27)
    at N:\Lunox\node_modules\@sapphire\shapeshift\dist\index.js:201:66
    at Array.reduce (<anonymous>)
    at StringValidator.parse (N:\Lunox\node_modules\@sapphire\shapeshift\dist\index.js:201:29)
    at ButtonBuilder.setURL (N:\Lunox\node_modules\@discordjs\builders\dist\index.js:632:34)
    at Object.run (N:\Lunox\src\commands\Message\Information\Help.js:20:68)
    at module.exports.run (N:\Lunox\src\events\botEvents\guild\messageCreate.js:66:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[AntiCrash] | [UnhandledRejection_Logs] | [end] : ===============

**Comment by adh319** [comment]
> [COMMAND] - help executed by BITS_gamer50082#4908 | verification in placeholder 1 (992403526133239829) [AntiCrash] | [UnhandledRejection_Logs] | [start] : =============== ExpectedConstraintError > s.string.url Invalid URL
> 
> Expected: expected to match an URL
> 
> Received: | ''
> 
> ```
> at Object.run (N:\Lunox\node_modules\@sapphire\shapeshift\dist\index.js:1595:27)
> at N:\Lunox\node_modules\@sapphire\shapeshift\dist\index.js:201:66
> at Array.reduce (<anonymous>)
> at StringValidator.parse (N:\Lunox\node_modules\@sapphire\shapeshift\dist\index.js:201:29)
> at ButtonBuilder.setURL (N:\Lunox\node_modules\@discordjs\builders\dist\index.js:632:34)
> at Object.run (N:\Lunox\src\commands\Message\Information\Help.js:20:68)
> at module.exports.run (N:\Lunox\src\events\botEvents\guild\messageCreate.js:66:17)
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> [AntiCrash] | [UnhandledRejection_Logs] | [end] : ===============

like i said before make sure u filled everyting in .env file... the details regarding of what u should fill are in config.js files. Please read Readme.md file again

**Comment by gamer50082** [comment]
i fix it already but reconnecting still
 and i made sure i put in the correct info

**Comment by gamer50082** [comment]
ame: process.env.NODE_NAME || "lava.link", // lavalink node name (anything you want)
            host: process.env.NODE_HOST || "lava.link", // lavalink host
            port: parseInt(process.env.NODE_PORT || "80"), //lavalink port
            password: process.env.NODE_PASSWORD || "youshallnotpass", //lavalink pass/auth
            secure: parseBoolean(process.env.NODE_SECURE || "false"), //lavalink secure "true/false"

**Comment by gamer50082** [comment]
in .env its empty

**Comment by adh319** [comment]
> i fix it already but reconnecting still and i made sure i put in the correct info

try use other lavalink server. u can join Lunox server for free lavalink

**Comment by gamer50082** [comment]
solve with ur lavalink thx
