### ISSUE TITLE
Node disconnecting (Returning Bad Response 400) when connecting to a secure node

### ISSUE THREAD

**Issue by OrdinaryEnder** [adh319/Lunox#54]
### Bug description

I do mess up with the config.js file, I added some node in there that is secure, and when did i try to connect they didn't connect at all

### Step to reproduce

Adding multiple nodes in config.js

### Operating system

Linux

### Nodejs version

v18.13.10

### Errors / Logs

```
[ERROR] Node LEXNET europe Error!: Error: Unexpected server response: 400
[WARN] Node LEXNET europe Disconnected!
[INFO] 33 Slash Commands Loaded!
[INFO] Node US Lavalink Ready!
[ERROR] Node OrdinaryLavallink Error!: Error: Unexpected server response: 400
[WARN] Node OrdinaryLavallink Disconnected!
```

**Comment by adh319** [comment]
this is node the code issue. aks about it on Poru client here https://github.com/parasop/poru or Lavalink repo here https://github.com/lavalink-devs/Lavalink
