### ISSUE TITLE
I tripped over a crutch

### ISSUE THREAD

**Issue by SashaXser** [adh319/Lunox#6]
[ERR_REQUIRE_ESM]: require() of ES Module /test2/node_modules/pretty-ms/index.js from /test2/src/commands/Slash/Information/About.js not supported.
WHY??

**Comment by SashaXser** [comment]
Change shitty-ms to ms

**Comment by adh319** [comment]
> [ERR_REQUIRE_ESM]: require() of ES Module /test2/node_modules/pretty-ms/index.js from /test2/src/commands/Slash/Information/About.js not supported. WHY??

did u use pretty-ms latest version? if yes. then use the same version as the package.json has.

**Comment by adh319** [comment]
sorry i forgot to update the package.json

**Comment by adh319** [comment]
check latest commit. i've updated the package.json
