### ISSUE TITLE
No commands work

### ISSUE THREAD

**Issue by RealAmethyst** [adh319/Lunox#66]
### Bug description

Whenever I try to use the play command or search command I get this in the bot console: [WARN] Errored Musikk#1352 (1161232410122395668) Error: Invalid URL
This also happens when I do the search command. I am not sure what I did wrong, I followed the instructions and the bot is running and online, but whenever I try the play or search command, that happens

### Step to reproduce

setup the bot, run it, try the play or search command.

### Operating system

Ubuntu 22.04 Linode VPS

### Nodejs version

18.18.0

### Errors / Logs

[WARN] Errored Musikk#1352 (1161232410122395668) Error: Invalid URL

**Comment by adh319** [comment]
did you perhaps leave some option on the env empty?

**Comment by RealAmethyst** [comment]
I did leave the owner and color stuff empty, but token, spotify, server and lavalink are configured.

**Comment by RealAmethyst** [comment]
I also got lavasource plugin and are using that. I want to play direct spotify links.

**Comment by adh319** [comment]
> I did leave the owner and color stuff empty, but token, spotify, server and lavalink are configured.

dont leave any option in the env emptied

**Comment by RealAmethyst** [comment]
Ok I'll configure the rest of the options.

**Comment by adh319** [comment]
> I also got lavasource plugin and are using that. I want to play direct spotify links.

put `spsearc` for `DEFAULT_PLATFORM` in the env

**Comment by RealAmethyst** [comment]
Thank you!

**Comment by RealAmethyst** [comment]
The plugin is only 1 file right? There were 2 release files on the github

**Comment by adh319** [comment]
> The plugin is only 1 file right? There were 2 release files on the github

use stable one

**Comment by RealAmethyst** [comment]
I'm using v3.9 something. latest stable. Is the color imbed rgb values or hex? Sorry for all questions, but I am new to this.

**Comment by adh319** [comment]
> I'm using v3.9 something. latest stable. Is the color imbed rgb values or hex? Sorry for all questions, but I am new to this.

hex withoud `#`

**Comment by RealAmethyst** [comment]
thanks! Now it loads and connects, but then I get this: Unhandled Rejection at: Promise { <rejected> TypeError: Cannot read properties of undefined (reading 'track') at Player.play (/root/Lunox/node_modules/poru/dist/src/Player/Player.js:79:31) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) } reason: TypeError: Cannot read properties of undefined (reading 'track') at Player.play (/root/Lunox/node_modules/poru/dist/src/Player/Player.js:79:31) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) [AntiCrash] | [UnhandledRejection_Logs] | [end] : ===============

**Comment by RealAmethyst** [comment]
Search command also gives me errors.

**Comment by RealAmethyst** [comment]
I'm pretty sure I did everything correctly, so I don't understand why it's giving me errors.

**Comment by RealAmethyst** [comment]
the git clone --single-branch --branch master https://github.com/Enour-Dev/Lunox.git command did not work on my end when setting it up, so I did just git clone repo, is that the issue here?

**Comment by adh319** [comment]
> the git clone --single-branch --branch master https://github.com/Enour-Dev/Lunox.git command did not work on my end when setting it up, so I did just git clone repo, is that the issue here?

i'll update the repo & do some changes. try clone it once again and fill everything on the env file. even the Link details.

**Comment by RealAmethyst** [comment]
ok. I'll just copy out the lavalink and .env then start from scratch.

**Comment by adh319** [comment]
once your errors fixed, please kindly close this issue.

**Comment by RealAmethyst** [comment]
will do, do I use the git clone repo command or the one that's on the github page?

**Comment by adh319** [comment]
> will do, do I use the git clone repo command or the one that's on the github page?

same thing... you choose it will clone the same repo

**Comment by RealAmethyst** [comment]
[DEBUG] Player Created From 1099342729084948571!
[AntiCrash] | [UnhandledRejection_Logs] | [start] : ===============
Unhandled Rejection at: Promise {
<rejected> TypeError: Cannot read properties of undefined (reading 'track')
at Player.play (/root/Lunox/node_modules/poru/dist/src/Player/Player.js:79:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} reason: TypeError: Cannot read properties of undefined (reading 'track')
at Player.play (/root/Lunox/node_modules/poru/dist/src/Player/Player.js:79:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[AntiCrash] | [UnhandledRejection_Logs]
| [end] : ===============

**Comment by RealAmethyst** [comment]
Looks like it's less errors than yesterday at least.

**Comment by adh319** [comment]
> Looks like it's less errors than yesterday at least.

check your lavalink config or you join to my discord server to test your bot using the freelavalink from my server

**Comment by RealAmethyst** [comment]
It's connecting to the lavalink fine, as I have logs from it via the other terminal window. I do however have IPv6 turned off, could that be an issue? In discord it sends an imbed with the track that should play, so it at least finds it.

**Comment by RealAmethyst** [comment]
I am using dafult java from ubuntu's apt manager if that has anything to do with anything.

**Comment by adh319** [comment]
> It's connecting to the lavalink fine, as I have logs from it via the other terminal window. I do however have IPv6 turned off, could that be an issue? In discord it sends an imbed with the track that should play, so it at least finds it.

i know its connecting but i think your application.yml is missing something. thats why i recomended you to test out the lavalink on my discord server. to see if it gives you the same errors

**Comment by RealAmethyst** [comment]
looks like IPV6 is not the issue.

**Comment by RealAmethyst** [comment]
ah ok. What is your server link?

**Comment by adh319** [comment]
i put it on the repo homepage
