### ISSUE TITLE
Can't use prefix commands

### ISSUE THREAD

**Issue by PawiX25** [adh319/Lunox#7]
When i use prefix command i always get error.
TypeError: Cannot read properties of undefined (reading 'get')
![Photo](https://user-images.githubusercontent.com/81538700/209482952-fe6c26ca-d7b3-446d-8c26-7d0c65171c6f.png)
![image](https://user-images.githubusercontent.com/81538700/209482976-97b01a8e-3012-4ccc-8cca-b5c3187b3f29.png)

**Comment by adh319** [comment]
did u change any code in the `messageCreate.js` file?

> When i use prefix command i always get error. TypeError: Cannot read properties of undefined (reading 'get') ![Photo](https://user-images.githubusercontent.com/81538700/209482952-fe6c26ca-d7b3-446d-8c26-7d0c65171c6f.png) ![image](https://user-images.githubusercontent.com/81538700/209482976-97b01a8e-3012-4ccc-8cca-b5c3187b3f29.png)

did u change any code in the `messageCreate.js` file?

**Comment by adh319** [comment]
Issue Fixed at this https://github.com/adh319/Lunox/commit/e9f6ef4b9f1b135903fa3e44b6bf047c7c7bb892

**Comment by PawiX25** [comment]
:)
