### ISSUE TITLE
Fix screenshots on readme.md

### ISSUE THREAD

**Issue by hikeri** [adh319/Lunox#83]
### Bug description

I noticed that screenshots on readme.md do not work. Apparently the links need to be updated.
![Screenshot](https://github.com/adh319/Lunox/assets/95499256/e784998e-f833-45f3-a99c-9c6e5b154ecb)

### Step to reproduce

Open readme.md

### Operating system

Doesn't matter

### Nodejs version

Doesn't matter

**Comment by adh319** [comment]
thanks will update it soon
